### ISSUE TITLE
自动剧情可以默认选最后一句

### ISSUE THREAD

**Issue by w1ssen** [babalae/better-wuthering-waves#4]
一般最后一个选项是推进剧情

**Comment by jiongjiongJOJO** [comment]
可以检测图标，类似崩铁的剧情，有箭头的图标优先选择就行。

**Comment by GlaxyMarco** [comment]
是的，吟霖角色剧情有段如果不选最后一项会卡循环。

**Comment by huiyadanli** [comment]
已经修改为默认选最后一项 https://github.com/babalae/better-wuthering-waves/releases/tag/0.12
